### ISSUE TITLE
Wrong license in the OpenStore

### ISSUE THREAD

**Issue by Anne017** [luksus42/recorder#1]
In the OpenStore : https://open-store.io/app/audio-recorder.luksus

This app is displayed as Proprietary, whereas the correct license is GNU General Public License v3.0.

![capture du 2018-10-20 13-48-19](https://user-images.githubusercontent.com/17686836/47255287-daf85900-d46e-11e8-9a80-60c84f64653d.png)

**Comment by luksus42** [comment]
Thanks for the hint.
It's fixed now.

Best regards,
Lukas




On Sat, 20 Oct 2018 04:48:56 -0700, Anne017 wrote:
> In the OpenStore : https://open-store.io/app/audio-recorder.luksus
> 
> This app is displayed as Proprietary, whereas the correct
> license is GNU General Public License v3.0.
> 
> ![capture du 2018-10-20
> 13-48-19](https://user-images.githubusercontent.com/17686836/47255287-daf85900-d46e-11e8-9a80-60c84f64653d.png)
> 
> 

-- 
Sent using Dekko from my Ubuntu device

--

**Comment by Anne017** [comment]
Wonderful!
This way people will not be afraid to install this super app!
The issue can be closed now.
