### ISSUE TITLE
Invisible encoded files

### ISSUE THREAD

**Issue by gbdomubpkm** [luksus42/recorder#12]
The encoded files .flac .spx .amr do not appear in the list of records: they are however well created and visible with file manager.

**Comment by gbdomubpkm** [comment]
Moreover,  think it would be nice to show file extensions that don't appear

**Comment by luksus42** [comment]
yeah, I already fixed this, but it was not in the test-build I provided to you.
What do you mean with "show file extensions that don't appear"?

**Comment by gbdomubpkm** [comment]
I would like to see the created record files displayed as in File Manager.
For example :

2020-10-07-19-44-07-666.wav 
and not
2020-10-07-19-44-07-666
in order to have a clearer identification.
See https://github.com/luksus42/recorder/issues/13

**Comment by luksus42** [comment]
fixed with 92c51091cfd651a68275ed83aa9744256380f52d

**Comment by gbdomubpkm** [comment]
Thanks

**Comment by gbdomubpkm** [comment]
Tested. Good. In use, i think now  it would be desirable to provide a means for group selection and deletion of recordings.
