### ISSUE TITLE
[Information] test encodings

### ISSUE THREAD

**Issue by gbdomubpkm** [luksus42/recorder#13]
For information, just so that you have a global vision between the proposed encodings, the created encodings (file manager), and thetefore what appears in your app
![Formats encodages](https://user-images.githubusercontent.com/50362604/95373431-47c7c080-08dd-11eb-9eac-3ea92a802960.png)
![fichiers audios file manager](https://user-images.githubusercontent.com/50362604/95373471-5615dc80-08dd-11eb-9494-5fc247a3c5d5.png)
![fichiers audios enregistrés](https://user-images.githubusercontent.com/50362604/95373499-5f9f4480-08dd-11eb-9b37-6d2dfe40c7c4.png)

**Comment by luksus42** [comment]
Fixed with #12
