### ISSUE TITLE
Can't record

### ISSUE THREAD

**Issue by CesarHerreraG** [luksus42/recorder#16]
I use the Recorder app very often. It turns out that when I make or receive a phone call, the Record app doesn't work well for me. If I put it to record it creates a file without sound. The only way to fix it is to restart the phone.

**Comment by CesarHerreraG** [comment]
I use the Record app very often. It turns out that when I make or receive a phone call, the Record app doesn't work well for me. If I put it to record it creates a file without sound. The only way to fix it is to restart the phone.

**Comment by luksus42** [comment]
Do you mean it doesn't work after a phone-call or while a phone-call?
Which device?
Which release-channel do you use (devel, RC, stable)?

**Comment by CesarHerreraG** [comment]
After. Now I have Candidate, but Stable is the same. I think it is a system problem.

**Comment by luksus42** [comment]
And which device are you using?

**Comment by CesarHerreraG** [comment]
Xiaomi Mi A2

**Comment by luksus42** [comment]
Can you please try to post the log of the recorder app in here, when it is not working?
You can use the Logviewer app for that.

**Comment by CesarHerreraG** [comment]
file:///home/phablet/.cache/upstart/application-click-audio-recorder.luksus_Recorder_1.1.0.log

**Comment by CesarHerreraG** [comment]
Creating a QMirClientScreen now

** (Recorder:3766): CRITICAL **: gst_audio_format_from_string: assertion 'format != NULL' failed
ALSA lib conf.c:3814:(snd_config_update_r) cannot access file /usr/share/alsa/alsa.conf
virtual QMediaService* AalServicePlugin::create(const QString&) "org.qt-project.qt.mediaplayer"
Using Hybris video sink
virtual QMediaPlayer::State AalMediaPlayerControl::state() const 

virtual QMediaPlayer::MediaStatus AalMediaPlayerControl::mediaStatus() const 

error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.173\" (uid=32011 pid=3766 comm=\"Recorder \") interface=\"com.canonical.libertine.Service.Operations\" member=\"list\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=6245 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.173\" (uid=32011 pid=3766 comm=\"Recorder \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"running\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=6245 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.173\" (uid=32011 pid=3766 comm=\"Recorder \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"last_error\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=6245 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.173\" (uid=32011 pid=3766 comm=\"Recorder \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"result\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=6245 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
qml: console.debug(container):  audio/x-matroska Matroska
qml: console.debug(container):  audio/ogg Ogg
qml: console.debug(container):  audio/x-wav WAV
qml: console.debug(container):  audio/x-rf64 Broadcast Wave Format
qml: console.debug(container):  audio/webm WebM
** Application is now active
qml: 0
codec: "audio/x-vorbis" 
container: "audio/ogg" 
channels: 1 
encodingMode: 0 
encodingQuality: 2 
bitrate: 32000 
volume: 1 

shm_open() failed: Permission denied
STATE: QMediaRecorder::RecordingState
virtual void AalMediaPlayerControl::stop() 

virtual void AalMediaPlayerControl::setMedia(const QMediaContent&, QIODevice*) 

setMedia() media:  QUrl("file:///home/phablet/.local/share/audio-recorder.luksus/records/2022-08-13-21-14-44-300.ogg")
setMedia() headers empty:  true
virtual QMediaPlayer::MediaStatus AalMediaPlayerControl::mediaStatus() const 

Setting media to:  QUrl("file:///home/phablet/.local/share/audio-recorder.luksus/records/2022-08-13-21-14-44-300.ogg")
PlaybackStatus changed to:  "stopped"
STATE: QMediaRecorder::StoppedState
m_surface is NULL, can't update video texture 

PlaybackStatus changed to:  "paused"
** Application is now inactive
qt.qpa.mirclient: Attempted to deliver an event to a non-existent window, ignoring.
Creating a QMirClientScreen now

** (Recorder:5018): CRITICAL **: gst_audio_format_from_string: assertion 'format != NULL' failed
ALSA lib conf.c:3814:(snd_config_update_r) cannot access file /usr/share/alsa/alsa.conf
virtual QMediaService* AalServicePlugin::create(const QString&) "org.qt-project.qt.mediaplayer"
Using Hybris video sink
virtual QMediaPlayer::State AalMediaPlayerControl::state() const 

virtual QMediaPlayer::MediaStatus AalMediaPlayerControl::mediaStatus() const 

error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.185\" (uid=32011 pid=5018 comm=\"Recorder \") interface=\"com.canonical.libertine.Service.Operations\" member=\"list\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=6245 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.185\" (uid=32011 pid=5018 comm=\"Recorder \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"running\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=6245 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.185\" (uid=32011 pid=5018 comm=\"Recorder \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"last_error\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=6245 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.185\" (uid=32011 pid=5018 comm=\"Recorder \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"result\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=6245 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
qml: console.debug(container):  audio/x-matroska Matroska
qml: console.debug(container):  audio/ogg Ogg
qml: console.debug(container):  audio/x-wav WAV
qml: console.debug(container):  audio/x-rf64 Broadcast Wave Format
qml: console.debug(container):  audio/webm WebM
** Application is now active
qml: 0
codec: "audio/x-vorbis" 
container: "audio/ogg" 
channels: 1 
encodingMode: 0 
encodingQuality: 2 
bitrate: 32000 
volume: 1 

shm_open() failed: Permission denied
STATE: QMediaRecorder::RecordingState
virtual void AalMediaPlayerControl::stop() 

virtual void AalMediaPlayerControl::setMedia(const QMediaContent&, QIODevice*) 

setMedia() media:  QUrl("file:///home/phablet/.local/share/audio-recorder.luksus/records/2022-08-13-21-18-50-154.ogg")
setMedia() headers empty:  true
virtual QMediaPlayer::MediaStatus AalMediaPlayerControl::mediaStatus() const 

Setting media to:  QUrl("file:///home/phablet/.local/share/audio-recorder.luksus/records/2022-08-13-21-18-50-154.ogg")
STATE: QMediaRecorder::StoppedState
PlaybackStatus changed to:  "stopped"
PlaybackStatus changed to:  "paused"
m_surface is NULL, can't update video texture 

virtual void AalMediaPlayerControl::stop() 

qt.qpa.mirclient: Attempted to deliver an event to a non-existent window, ignoring.
qt.qpa.mirclient: Attempted to deliver an event to a non-existent window, ignoring.
qt.qpa.mirclient: Attempted to deliver an event to a non-existent window, ignoring.

**Comment by CesarHerreraG** [comment]
I don't know how to send the file. Sorry.

**Comment by CesarHerreraG** [comment]
Something may be usefull. One people can't save a video with sound until he restarts the phone. (Same for me).

**Comment by luksus42** [comment]
> Something may be usefull. One people can't save a video with sound until he restarts the phone. (Same for me).

Yes, that is the same issue.
The relevant line is: "shm_open() failed: Permission denied"

I saw that before, but I don't believe that it has something to do, with the app itself.
Maybe the call app keeps the microphone occupied after a call...

We need to investigate that further. I will inform here, if we found something.
For reference: https://github.com/ubports/ubuntu-touch/issues/2022

**Comment by CesarHerreraG** [comment]
Thanks

**Comment by CesarHerreraG** [comment]
One people with a "Xiaomi Note 9 Pro" has the same problems.

**Comment by luksus42** [comment]
Since this is clearly not an issue of the recorder app itself, I close this.
