### ISSUE TITLE
encoding of audio

### ISSUE THREAD

**Issue by ksalver** [luksus42/recorder#2]
when trying to use other than 
audio/ogg , p.ex audio/x-wav ,
then recording button shows an error.
my reason to change: when sending audio via SIGNAL (textsecure) to an iPhone in .ogg format the SIGNAL client cannot open ( i think that this the restriction in apples ios ; no codec for .ogg )

**Comment by luksus42** [comment]
Hi,
it seems, that you have to choose valid codec-container-pairs. For example it is not possible to save an mp3-encoded track into a wav-container.
I did some tests and for the audio/x-wav container it should be possible to choose the codecs "audio/x-alaw" and "audio/x-mulaw".
Another valid pair would be codec "audio/AMR" and container "video/quicktime, variant=3gpp"

Anyway, there is a bug #3 which causes that the file extension is always "ogg", regardless which container-format is set.
But the file-manager for example, still identifies the wav-file as wav (watch the file icon), even if the extension is "ogg".

**Comment by luksus42** [comment]
fixed with fa3d042a67f66093baf37b23436b37d47bd2b4e8
